# --------------------------- #
# SETTINGS SECTION
# --------------------------- #
SETTINGS:
    # number of concurrent threads
    THREADS: 1

    # number of retries for ANY action
    ATTEMPTS: 5
    
    # account range.
    # BY DEFAULT: [0, 0] - all accounts
    # [3, 5] - only 3 4 5 accounts
    # [7, 7] - only 7 account
    ACCOUNTS_RANGE: [0, 0]
    
    # WORKS ONLY IF ACCOUNTS_RANGE IS [0, 0]
    # exact accounts to use.
    # BY DEFAULT: [] - all accounts
    # Example: [1, 4, 6] - bot will use only 1, 4 and 6 accounts
    EXACT_ACCOUNTS_TO_USE: []
    
    SHUFFLE_WALLETS: true

    # pause between attempts
    PAUSE_BETWEEN_ATTEMPTS: [3, 10]

    # pause between swaps
    PAUSE_BETWEEN_SWAPS: [3, 10]
    
    # pause in seconds between accounts
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [3, 10]
    
    # pause in seconds between actions
    RANDOM_PAUSE_BETWEEN_ACTIONS: [3, 10]
    
    # random pause before start of every account
    # to make sure that all accounts will be started at different times
    RANDOM_INITIALIZATION_PAUSE: [3, 30]
    
    # if true, bot will send logs to telegram
    SEND_TELEGRAM_LOGS: false
    # telegram bot token
    TELEGRAM_BOT_TOKEN: "12317283:lskjalsdfasdfasd-sdfadfasd"
    # telegram users ids
    TELEGRAM_USERS_IDS: [235123432]

    # wait for transaction confirmation in seconds
    WAIT_FOR_TRANSACTION_CONFIRMATION_IN_SECONDS: 240

FLOW:
    # if task from database failed, bot will skip it
    # if false, bot will stop and show error
    SKIP_FAILED_TASKS: false



ZERO_EXCHANGE_SWAPS:
    # percent of balance to swap
    BALANCE_PERCENT_TO_SWAP: [5, 10]
    # random number of swaps
    NUMBER_OF_SWAPS: [1, 3]


RPCS:
    ZEROG: ["https://evmrpc-testnet.0g.ai"]


CAPTCHA:
    # API KEY for solvium
    # https://t.me/solvium_crypto_bot
    # https://t.me/solvium_crypto_bot
    SOLVIUM_API_KEY: "xxxxxxxxxxxxxxxxxxxxxxx"


    USE_NOCAPTCHA: true
    # nocaptcha.io/register?c=SWVtru
    # API KEY for faucet
    NOCAPTCHA_API_KEY: "4d582279-a8fe-4ec3-888f-72a7f141d6b6"


OTHERS:
    SKIP_SSL_VERIFICATION: true
    USE_PROXY_FOR_RPC: true
  
PUZZLEMANIA:
    USE_REFERRAL_CODE: false
    INVITES_PER_REFERRAL_CODE: [1, 3]
    COLLECT_REFERRAL_CODE: true

CRUSTY_SWAP:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Optimism", "Base"]
    AMOUNT_TO_REFUEL: [0.0003, 0.0004]
    MINIMUM_BALANCE_TO_REFUEL: 99999
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999
    BRIDGE_ALL: false
    BRIDGE_ALL_MAX_AMOUNT: 0.01

# --------------------------- #
# EXCHANGES SECTION
# --------------------------- #
EXCHANGES:
    name: "OKX"  # Supported: "OKX", "BITGET"
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    secretKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    passphrase: 'xxxxxxx'  
    withdrawals:
        - currency: "ETH" # ONLY ETH
          networks: ["Arbitrum", "Optimism"] # ["Arbitrum", "Base", "Optimism"]
          min_amount: 0.0004
          max_amount: 0.0006
          max_balance: 0.005
          wait_for_funds: true
          max_wait_time: 99999  # in seconds
          retries: 3